
package vista;

import controlador.VentanaController;

import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;

import javax.swing.ListModel;

import modelo.Humano;
import modelo.Usuario;

/**
 *
 * @author juanfe
 */
public class Ventana extends javax.swing.JFrame {

    /** Creates new form Ventana */
    
    private DefaultListModel<Usuario> u1;
    
    public Ventana(VentanaController vc) {
        initComponents();
        this.jButton1.addActionListener(vc);
        this.cHumano.addActionListener(vc);
        this.interactuar.addActionListener(vc);
        this.jButton3.addActionListener(vc);
        init();
        this.setVisible(true);
    }


    public JList<Usuario> getJList1() {
        return jList1;
    }

    public void init(){
        this.jButton3.setEnabled(false);
        this.cHumano.setEnabled(false);
        this.interactuar.setEnabled(false);
        this.u1=new DefaultListModel<Usuario>();
        this.jList1.setModel(u1);
    }
    
    public void redSocialCreada(){
        this.jButton3.setEnabled(true);
        this.cHumano.setEnabled(true);
        this.interactuar.setEnabled(true);
    }


    public void setCHumano(JButton cHumano) {
        this.cHumano = cHumano;
    }

    public JButton getCHumano() {
        return cHumano;
    }

    public void setInteractuar(JButton interactuar) {
        this.interactuar = interactuar;
    }

    public JButton getInteractuar() {
        return interactuar;
    }

    public void setJButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getJButton1() {
        return jButton1;
    }

    public void setJButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JButton getJButton3() {
        return jButton3;
    }


    public DefaultListModel<Usuario> getU1() {
        return u1;
    }
    
    public void actualizaListas(Iterator<Usuario> it)
    {
            this.u1.clear();
            while (it.hasNext())
            {
                    this.u1.addElement(it.next());
            }
            this.repaint();
    }
    public void agregarMensaje(String mensaje){
        this.jTextArea1.append(mensaje+" \n");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cHumano = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        interactuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jButton1.setText("Crear Red Social");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        cHumano.setText("Crear humano");
        jPanel1.add(cHumano);

        jButton3.setText("Crear robot");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7);

        jPanel4.add(jPanel6);

        jPanel2.add(jPanel4);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jList1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Usuarios");
        jPanel5.add(jLabel1);

        interactuar.setText("Ver Red Social");
        jPanel5.add(interactuar);

        jPanel3.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cHumano;
    private javax.swing.JButton interactuar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Usuario> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
