
package vista;

import controlador.VentanaMenuRedSocialController;


import java.awt.event.WindowAdapter;

import java.awt.event.WindowEvent;

import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

import modelo.Usuario;

/**
 *
 * @author juanfe
 */
public class VentanaMenuRedSocial extends javax.swing.JFrame {

    /** Creates new form VentanaMenuRedSocial */
    
    
    public VentanaMenuRedSocial(VentanaMenuRedSocialController vmrs) {
        initComponents();
        this.setVisible(true);
        this.jButton1.addActionListener(vmrs);
        this.jrbfoto.addActionListener(vmrs);
        this.jrbtexto.addActionListener(vmrs);
        this.jrbvideo.addActionListener(vmrs);
        this.jbgestion.addActionListener(vmrs);
        
    }


    public JRadioButton getJrbfoto() {
        return jrbfoto;
    }

    public JRadioButton getJrbtexto() {
        return jrbtexto;
    }

    public JRadioButton getJrbvideo() {
        return jrbvideo;
    }

    public JTextField getJtfdescripcion() {
        return jtfdescripcion;
    }

    public JTextField getJtfdur() {
        return jtfdur;
    }

    public JTextField getJtflugar() {
        return jtflugar;
    }

    public JTextField getJtfres() {
        return jtfres;
    }
    
    public JTextField getJtfFechaSuceso(){
        return jTextField3;
    }
    
    public JTextField getJtfvisibilidad() {
        return jtfvisibilidad;
    }
    public JTextField getJtfNomSuceso() {
        return jTextField2;
    }
    public JTextField getJtfLugarSuceso() {
        return jtflugar;
    }
    

    public JRadioButton getJrbcomerc() {
        return jrbcomerc;
    }

    public JRadioButton getJrbsocial() {
        return jrbsocial;
    }


    public ButtonGroup getBg1() {
        return bg1;
    }

    public ButtonGroup getBg2() {
        return bg2;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jrbvideo = new javax.swing.JRadioButton();
        jrbcomerc = new javax.swing.JRadioButton();
        jrbfoto = new javax.swing.JRadioButton();
        jrbsocial = new javax.swing.JRadioButton();
        jrbtexto = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfdescripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfdur = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtflugar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfvisibilidad = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jbgestion = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 4));

        jButton1.setText("Ver Publicaciones");
        getContentPane().add(jButton1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        jButton3.setText("Crear Publicacion");
        getContentPane().add(jButton3);

        jPanel6.setLayout(new java.awt.GridLayout(3, 2));

        bg1.add(jrbvideo);
        jrbvideo.setText("Video");
        jPanel6.add(jrbvideo);

        bg2.add(jrbcomerc);
        jrbcomerc.setText("Comercial");
        jrbcomerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbcomercActionPerformed(evt);
            }
        });
        jPanel6.add(jrbcomerc);

        bg1.add(jrbfoto);
        jrbfoto.setText("Foto");
        jPanel6.add(jrbfoto);

        bg2.add(jrbsocial);
        jrbsocial.setText("Social");
        jPanel6.add(jrbsocial);

        bg1.add(jrbtexto);
        jrbtexto.setText("Texto");
        jPanel6.add(jrbtexto);

        getContentPane().add(jPanel6);

        jPanel3.setLayout(new java.awt.GridLayout(2, 2));

        jLabel5.setText("Descripcion");
        jPanel3.add(jLabel5);
        jPanel3.add(jtfdescripcion);

        jLabel7.setText("Duracion");
        jPanel3.add(jLabel7);
        jPanel3.add(jtfdur);

        getContentPane().add(jPanel3);

        jPanel5.setLayout(new java.awt.GridLayout(3, 2));

        jLabel6.setText("    Resolucion");
        jPanel5.add(jLabel6);
        jPanel5.add(jtfres);

        jLabel8.setText("    Lugar");
        jPanel5.add(jLabel8);
        jPanel5.add(jtflugar);

        jLabel9.setText("    Visibilidad");
        jPanel5.add(jLabel9);
        jPanel5.add(jtfvisibilidad);

        getContentPane().add(jPanel5);

        jButton4.setText("Crear grupo de chat");
        getContentPane().add(jButton4);

        jPanel8.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setText("Nombre");
        jPanel8.add(jLabel4);
        jPanel8.add(jTextField4);

        getContentPane().add(jPanel8);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9);

        jButton5.setText("Crear suceso");
        getContentPane().add(jButton5);

        jPanel11.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Nombre");
        jPanel11.add(jLabel1);
        jPanel11.add(jTextField2);

        getContentPane().add(jPanel11);

        jPanel10.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setText("Descripcion");
        jPanel10.add(jLabel2);
        jPanel10.add(jTextField1);

        getContentPane().add(jPanel10);

        jPanel12.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setText("Fecha");
        jPanel12.add(jLabel3);
        jPanel12.add(jTextField3);

        getContentPane().add(jPanel12);

        jbgestion.setText("Gestion Amigos");
        getContentPane().add(jbgestion);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel15);

        pack();
    }//GEN-END:initComponents

    private void jrbcomercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbcomercActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbcomercActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbgestion;
    private javax.swing.JRadioButton jrbcomerc;
    private javax.swing.JRadioButton jrbfoto;
    private javax.swing.JRadioButton jrbsocial;
    private javax.swing.JRadioButton jrbtexto;
    private javax.swing.JRadioButton jrbvideo;
    private javax.swing.JTextField jtfdescripcion;
    private javax.swing.JTextField jtfdur;
    private javax.swing.JTextField jtflugar;
    private javax.swing.JTextField jtfres;
    private javax.swing.JTextField jtfvisibilidad;
    // End of variables declaration//GEN-END:variables

}
